name: kasirr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.8.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/Untitled design.png
    - asset/image/Untitled_design__1_-removebg-preview (1).png
    - asset/image/mtcha.jpg
    - asset/image/otml.jpg
    - asset/image/choco.jpg
    - asset/image/rdvjpg.jpg
    - asset/image/bckjpg.jpg